# Generated by Django 6.1.1 on 2026-09-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('refRayon', models.AutoField(primary_key=True, serialize=False)),
                ('titreRayon', models.CharField(max_length=200)),
                ('typeRayon', models.CharField(max_length=50)),
            ],
        ),
    ]
