# Generated by Django 6.1.1 on 2026-09-17 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rayon'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFabrication',
            field=models.DateField(default=datetime.date(2006, 11, 10)),
        ),
    ]
