# Generated by Django 6.1.1 on 2026-09-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_statut', to='application.statut'),
        ),
    ]
